### ISSUE TITLE
Apache Commons Logging (JCL) binding

### ISSUE THREAD

**Issue by pmwmedia** [tinylog-org/tinylog#44]
Reimplementation of [Apache Commons Logging (JCL) binding](https://github.com/pmwmedia/tinylog/tree/v1.2/jcl-binding) for tinylog 2.0:

- [x] Create project jcl-tinylog
- [x] Implement [LogFactory](https://commons.apache.org/proper/commons-logging/apidocs/org/apache/commons/logging/LogFactory.html)
- [x] Write JUnit tests
- [x] Register log factory as service
- [x] Add readme text file

**Comment by totszwai** [comment]
Desperately need this.

How do I use the log4j-facade so that the Apache common logging would use your tinylog instead?

Exception in thread "Thread-3" java.lang.NoSuchMethodError: org.apache.log4j.Logger.log(Ljava/lang/String;Lorg/apache/log4j/Priority;Ljava/lang/Object;Ljava/lang/Throwable;)V
	at org.apache.commons.logging.impl.Log4JLogger.debug(Log4JLogger.java:155)
	at org.apache.http.client.protocol.RequestAuthCache.process(RequestAuthCache.java:77)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:183)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.blah.MyStuff.sendPOST(MyStuff.java:44)


Is there a quick workaround that I can put in?
