### ISSUE TITLE
ConcurrentModificationException in org.pmw.tinylog.Configurator.init

### ISSUE THREAD

**Issue by trebouillon** [tinylog-org/tinylog#93]
While initializing the logger I got the following exception:

```
Caused by java.util.ConcurrentModificationException
       at java.util.Hashtable$HashIterator.nextEntry(Hashtable.java:727)
       at java.util.Hashtable$KeyIterator.next(Hashtable.java:768)
       at org.pmw.tinylog.Configurator.init(Unknown Source)
       at org.pmw.tinylog.Logger.<clinit>(Unknown Source)
       at org.pmw.tinylog.Configurator.activate(Unknown Source)
       at myapp.log.Logging.initialize(Logging.java:13)
       at myapp.initialization.AppInitializer.init(AppInitializer.java:71)
       at myapp.MyApplication.onCreate(MyApplication.java:59)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4950)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5740)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
```

Device: Lenovo K5 Note
API: 23 (6.0)

Are there changes in version 2 which would make this issue obsolete?

**Comment by pmwmedia** [comment]
The cause is that the system properties are modified while loading tinylog's configuration (see [Configurator, line 735](https://github.com/pmwmedia/tinylog/blob/v1.3/tinylog/src/org/pmw/tinylog/Configurator.java#L735)). I will create a copy of the system properties and iterate of this copy to fix this issue.

**Comment by pmwmedia** [comment]
@trebouillon  I have just released a fix: https://tinylog.org/download. Can you test it?

**Comment by trebouillon** [comment]
Thank you for the quick fix. As this only happened once so far I think this is hard to reproduce. But I will update to the latest release.
